### ISSUE TITLE
1054 Error

### ISSUE THREAD

**Issue by Jokele** [daviddeutsch/aec.valanx.org#1]
Hi David.

As requested I am using this venue for sharing, here is the issue I am having:

When I click register after entering all the users registration information I get thrown to the joomla error page with a stated 1054.

The user is registered and everything else seems to trigger, but the error page is there.

Have you seen this before?

**Comment by daviddeutsch** [comment]
Sorry, is this an AEC bug or a bug with the valanx.org/aec page? I kinda think you want to file this at [valanx/aec](https://github.com/valanx/aec/issues)? If you do, make sure to include a link or a screenshot!

**Comment by Jokele** [comment]
I believe it to be an AEC bug, or a setup issue. There is not much to see except a custom error page with 1054 and no additional information on it.

**Comment by daviddeutsch** [comment]
In that case, yes - definitely open a bug in the aec repository :wink:

**Comment by Jokele** [comment]
I must have misunderstood, I thought this was the right place. Just in case, here is some additional info:

Warning: array_reverse() expects parameter 1 to be array, string given in components/com_acctexp/classes/acctexp.invoice.class.php on line 1771

Warning: Invalid argument supplied for foreach() in components/com_acctexp/classes/acctexp.invoice.class.php on line 1773

**Comment by daviddeutsch** [comment]
Yeah, this is the repository for http://valanx.org/aec - the website, not the software. Please follow the link in my original reply to open an AEC issue.
